version: 2.1
executors:
  docker-publisher:
    docker:
      - image: cimg/base:stable
jobs:
  build-and-push:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
            docker build -t riya7725/repo1:latest .
            docker push riya7725/repo1:latest

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build-and-push
