version: 2.1
jobs:
  build-and-push:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
            docker build -t riya7725/repo1:latest .
            docker push riya7725/repo1:latest

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build-and-push
h
